### ISSUE TITLE
sbercloud_compute_instance cant create without volume - GPSSD error

### ISSUE THREAD

**Issue by fufar** [sbercloud-terraform/terraform-provider-sbercloud#115]
### Terraform Version
Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/sbercloud-terraform/sbercloud v1.5.1

### Affected Resource(s)
- sbercloud_compute_instance

### Terraform Configuration Files
Example from 
https://registry.terraform.io/providers/sbercloud-terraform/sbercloud/latest/docs/resources/compute_instance#instance-with-attached-volume

```hcl
resource "sbercloud_evs_volume" "myvolume" {
  name              = "myvolume"
  availability_zone = "cn-north-4a"
  volume_type       = "SAS"
  size              = 10
}

resource "sbercloud_compute_instance" "myinstance" {
  name              = "myinstance"
  image_id          = "ad091b52-742f-469e-8f3c-fd81cadf0743"
  flavor_id         = "s6.small.1"
  key_pair          = "my_key_pair_name"
  security_groups   = ["default"]
  availability_zone = "ru-moscow-1a"

  network {
    uuid = "55534eaa-533a-419d-9b40-ec427ea7195a"
  }
}

resource "sbercloud_compute_volume_attach" "attached" {
  instance_id = sbercloud_compute_instance.myinstance.id
  volume_id   = sbercloud_evs_volume.myvolume.id
}
```

### Panic Output
```{"error":{"message":"rootVolume type[GPSSD] is not exist.","code":"Ecs.0005","details":[{"code":"Ecs.0043"}]}}```

**Comment by kolsean** [comment]
@niuzhenguo Is it possible to change the default provider value to `SSD` or make `system_disk_type` as `required` argument in `terraform-provider-huaweicloud`?  https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/huaweicloud/resource_huaweicloud_ecs_instance_v1.go#L595

**Comment by niuzhenguo** [comment]
@kolsean suggest to make it required in sbercloud docs.
