### ISSUE TITLE
Import problem, ECS ipv4 gets imported as fixed_ip_v6 

### ISSUE THREAD

**Issue by SlaRob** [sbercloud-terraform/terraform-provider-sbercloud#125]
Hello.

I'm trying to upgrade my infrastructure to  use latest version of the provider(v1.6.0). During this process i had to delete ecs from terraform state and do an import. And here is a problem, for example i do

```
terraform import sbercloud_compute_instance.resty[0] ${my_resty_id}
```
and get this in terraform state network block for the resource
```
            "network": [
              {
                "access_network": false,
                "fixed_ip_v4": "",
                "fixed_ip_v6": "10.1.1.1",
                "ipv6_enable": true,
                "mac": "nic mac address",
                "port": "pord uuid",
                "source_dest_check": true,
                "uuid": "nic uuid"
              }
            ],
```
the problem is, network parameter ipv6_enable has true value by default while importing and we do not use ipv6 at all. This parameter forces replacement of full ECS instance if i set ipv6_enable = false, and of course i don't want it to be replaced. If i set 
```
lifecycle {
ignore_changes = [ network[0].ipv6_enable ]
```
my dns records, which use fixed_ip_v4 receive empty filed and try to replace actual ipv4 with it so i also cannot use it. Before trying to manually edit my giant state file with possible risks of corrupting it i want to ask you if there is a workarount or a possible hotfix for this kind of situation. There is no way to modify nic in cloud console to change ipv6 parameters, maybe api is the way, will try it later.
I'm aware that this may as well be a problem with a parent huaweicloud provider. Still, maybe you have an answer how to avoid this. 

The way to reproduce it is obvious, try to import ecs to state.

**Comment by ShiChangkuo** [comment]
@SlaRob is "10.1.1.1" a real IP address of your ECS instance?

**Comment by ShiChangkuo** [comment]
> @ShiChangkuo it's just an example to point that ip of version 4 gets written to the fixed_ip_v6 field during import.

There is a bug for some IP addresses, such as 10.250.4.192, so I want to check the real IP address.

**Comment by ShiChangkuo** [comment]
got it, will fix it in the next release.
