### ISSUE TITLE
Problem with range port in sbercloud_network_acl_rule

### ISSUE THREAD

**Issue by Uiopas** [sbercloud-terraform/terraform-provider-sbercloud#141]
Hello everyone, when I try to create an network_acl_rule with range port, I get an error. Details below.

### Terraform Version
Terraform v1.1.9

### Affected Resource(s)
- sbercloud_network_acl_rule

### Terraform Configuration Files
```hcl
resource "sbercloud_network_acl_rule" "rules" {
  protocol               = "tcp"
  ip_version             = 4
  action                 = "allow"
  destination_port       = "1-100"
}
```

### Expected Behavior
Terraform should have created a rule with a range port, as described in the documentation for this resource. 
```
For a port number range, enter two port numbers connected by a hyphen (-). For example, 1-100.
```

### Actual Behavior

```
│ Error: Bad request with: [POST https://vpc.ru-moscow-1.hc.sbercloud.ru/v2.0/fwaas/firewall_rules], error message: {"NeutronError":{"message":"Invalid input for destination_port. Reason: Port '1-100' is not a valid number..","type":"HTTPBadRequest","detail":""}}
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by Wakeup777** [comment]
I also ran into this problem. I think is a serious bug, because i have to write the hundred thousand rules instead the one rule. it's not DRY principle

**Comment by Shesoff** [comment]
Have same problem. Fix it please

**Comment by vodeneko** [comment]
Need to correct documentation.
Working config
resource "sbercloud_network_acl_rule" "rule_01" {
  protocol         = "tcp"
  ip_version       = 4
  action           = "allow"
  destination_port = "1**:**100"
}
