### ISSUE TITLE
DCS (Redis) users and ACL management using Terraform provider

### ISSUE THREAD

**Issue by vlan2012** [sbercloud-terraform/terraform-provider-sbercloud#194]
**Actual Behavior**: There is no way to manage DCS (Redis) users and ACL using Terraform provider
**Expected Behavior**: We can manage DCS users and ACL using your Terraform provider
**Workaround**: no workaround using UI

Feature request from Amazme project

**Comment by HypnoChaka** [comment]
Its cannot be implemented in our provider.
