### ISSUE TITLE
DCS (Redis) configuration parameters management using Terraform provider

### ISSUE THREAD

**Issue by vlan2012** [sbercloud-terraform/terraform-provider-sbercloud#195]
**Actual Behavior**: There is no way to manage DCS (Redis) configuration parameters using Terraform provider
**Expected Behavior**: We can manage DCS configuration parameters using your Terraform provider, at least those parameters which can be tuned using UI.
**Workaround**: using UI to tune some parameters

Feature request from Amazme project

**Comment by Ccaswell42** [comment]
Testing the possibility of adding this functionality

**Comment by Ccaswell42** [comment]
Will be implemented in the next release.

**Comment by HypnoChaka** [comment]
Done. Please check it.
