### ISSUE TITLE
Restore DCS (Redis) backup to a new DCS instance using Terraform provider

### ISSUE THREAD

**Issue by vlan2012** [sbercloud-terraform/terraform-provider-sbercloud#196]
**Actual Behavior**: There is no way to restore DCS (Redis) backup to a new DCS using Terraform provider
**Expected Behavior**: We can restore DCS backup to a new DCS using your Terraform provider
**Workaround**: using UI

Feature request from Amazme project

**Comment by Ccaswell42** [comment]
Testing the possibility of adding this functionality

**Comment by HypnoChaka** [comment]
Done. Please check it.
