### ISSUE TITLE
RDS (PostgreSQL) configuration parameters management using Terraform provider

### ISSUE THREAD

**Issue by vlan2012** [sbercloud-terraform/terraform-provider-sbercloud#200]
**Actual Behavior**: There is no way to manage RDS configuration parameters using Terraform provider
**Expected Behavior**: We can manage RDS configuration parameters using your Terraform provider, at least those parameters which can be tuned using UI.
**Workaround**: using UI to tune some parameters

Feature request from Amazme project

**Comment by Ccaswell42** [comment]
Testing the possibility of adding this functionality
