### ISSUE TITLE
Restore RDS (PostgreSQL) backup to a new RDS instance using Terraform provider

### ISSUE THREAD

**Issue by vlan2012** [sbercloud-terraform/terraform-provider-sbercloud#201]
**Actual Behavior**: There is no way to restore RDS backup to a new RDS using Terraform provider
**Expected Behavior**: We can restore RDS backup to a new RDS using your Terraform provider
**Workaround**: using UI

Feature request from Amazme project

**Comment by Ccaswell42** [comment]
Testing the possibility of adding this functionality

**Comment by Ccaswell42** [comment]
Done. Please check it.  See `restore` block: https://github.com/sbercloud-terraform/terraform-provider-sbercloud/blob/master/docs/resources/rds_instance.md
