### ISSUE TITLE
Ability to change "direct connect" and "endpoint gateway" 

### ISSUE THREAD

**Issue by negative-creep90** [sbercloud-terraform/terraform-provider-sbercloud#207]
Hi there!

Could you please add the support for "direct connect" and "endpoint gateway" ability  to setup over api? as example i've find it here
https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/docs/resources/dc_virtual_gateway.md
https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/docs/resources/ga_endpoint.md

**Comment by HypnoChaka** [comment]
Testing the possibility of adding this functionality.

**Comment by Ccaswell42** [comment]
Sorry, but now we don't have the possibility to add this functionality
