### ISSUE TITLE
Не работающий параметр "device" в ресурсе sbercloud_compute_volume_attach.

### ISSUE THREAD

**Issue by AlexeyGacenko** [sbercloud-terraform/terraform-provider-sbercloud#208]
Коллеги, добрый день.

В рамках инфраструктуры через **Terraform** модуль описываем процесс монтирования ранее созданного диска к серверу. В ходе процесса обозначаем в ресурсе следующие параметры.
 
resource "sbercloud_compute_volume_attach" "attached1" {
  instance_id = "0df56bea-0049-46ac-bf29-2ba8f314a5b0"
  volume_id   = "a8613bbd-ba58-4ab1-92cd-756a0d52ad81"
  device         = "/dev/vdd"
}
 
resource "sbercloud_compute_volume_attach" "attached2" {
  instance_id = "0df56bea-0049-46ac-bf29-2ba8f314a5b0"
  volume_id   = "e4ec0dd2-d334-4f99-baf5-1fec2a7579c0"
  device         = "/dev/vdf"
}

В результате наблюдаем следующую картину не соответствующую описанию параметра "device":
 
```
$ lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda          254:0    0   40G  0 disk 
├─vda1       254:1    0    1K  0 part 
├─vda2       254:2    0 39,6G  0 part 
│ ├─vg0-swap 253:0    0  1,9G  0 lvm  [SWAP]
│ ├─vg0-var  253:1    0  4,7G  0 lvm  /var
│ ├─vg0-home 253:2    0   14G  0 lvm  /home
│ ├─vg0-tmp  253:3    0  1,9G  0 lvm  /tmp
│ ├─vg0-usr  253:4    0  4,7G  0 lvm  /usr
│ └─vg0-root 253:5    0  9,3G  0 lvm  /
└─vda5       254:5    0  365M  0 part /boot
vdb          254:16   0   11G  0 disk 
vdc          254:32   0   10G  0 disk 
```

Дополнительные диски примонтированы в /dev/vdb, /dev/vdc.
 
Исходя из этого есть вопрос, почему не работает назначение конкретного **volume** для диска при монтировании? Если процесс назначения происходит при первой инициализации сервера, а версия провайдера **Sbercloud** 1.11.2.

**Comment by Ccaswell42** [comment]
https://support.hc.sbercloud.ru/api/ecs/en-us_topic_0022472987.html
<img width="647" alt="edvice" src="https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/95140056/6cf3d1dd-08b2-41db-a850-0cb5d4272b4d">
