### ISSUE TITLE
Please add huaweicloud_identity_group_role_assignment functionality

### ISSUE THREAD

**Issue by DmitryNH** [sbercloud-terraform/terraform-provider-sbercloud#220]
Actual Behavior: function not exist
Expected Behavior: function should exist
How to replicate the environment in which the problem occurs: N/A

Please add huaweicloud_identity_group_role_assignment functionality https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/docs/resources/identity_group_role_assignment.md
Request from MegaMarket

**Comment by HypnoChaka** [comment]
Testing the possibility of adding this functionality.

**Comment by Ccaswell42** [comment]
We already have this functionality. Resource called `sbercloud_identity_role_assignment`
and works like `huaweicloud_identity_group_role_assignment`.

https://github.com/sbercloud-terraform/terraform-provider-sbercloud/blob/master/docs/resources/identity_role_assignment.md
