### ISSUE TITLE
SSH Key name not found

### ISSUE THREAD

**Issue by NetologyServiceAccount** [sbercloud-terraform/terraform-provider-sbercloud#225]
никак не получается пройти пример ТФ-кода
из
https://github.com/sbercloud-terraform/terraform-provider-sbercloud/tree/master/examples/cce/workers-in-different-AZs

Создал по readme VPC, subnet и key pair через веб-консоль.

При создании sbercloud_cce_node.cce_01_node[0]
SSH Key name KeyPair-tut1 not found
но она же есть?
и даже если руками идти ноду создавать то предлагается к выбору?

Terraform v1.3.7
on linux_amd64
![keypair2](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/15832523/ea54789d-e681-4674-955b-2c992e72bf07)
[main.tf.txt](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/files/12485936/main.tf.txt)

+ provider [tf.repo.sbc.space/sbercloud-terraform/sbercloud](http://tf.repo.sbc.space/sbercloud-terraform/sbercloud) v1.11.3

пробовал и с Terraform v1.5.5

полный текст ошибки тф:
sbercloud_cce_node.cce_01_node[0]: Creating...
╷
│ Error: error creating Node: Bad request with: [POST https://cce.ru-moscow-1.hc.sbercloud.ru/api/v3/projects/1b1b6ee72c7c49f8b89a95568365b985/clusters/c7e4af64-40f9-11ee-9b7a-0255ac100085/nodes], error message: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","code":400,"errorCode":"CCE.01400001","errorMessage":"Invalid request.","error_code":"CCE_CM.0004","error_msg":"Request is invalid","message":"SSH Key name KeyPair-3b5e not found","reason":"BadRequest"}
│
│   with sbercloud_cce_node.cce_01_node[0],
│   on [main.tf](http://main.tf/) line 45, in resource "sbercloud_cce_node" "cce_01_node":
│   45: resource "sbercloud_cce_node" "cce_01_node" {
![keypair](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/15832523/c640cbda-0bd1-45b9-98be-d28960dc1f23)

**Comment by HypnoChaka** [comment]
Добрый день! А вы с terraform работаете под тем же пользователем, под которым создавали этот key pair?

**Comment by NetologyServiceAccount** [comment]
Оказывается, ключевые пары привязаны к IAM-зерам.
то есть если пару вы создали от корневого пользователя, а ТФ запускаете от IAM-юзера -- ключ не найдётся.

Ходить в тф и на вебконсоль надо от одного пользователя.
