### ISSUE TITLE
Error: [DEBUG] cannot find the tenant: <my-tenant>

### ISSUE THREAD

**Issue by sergeso** [sbercloud-terraform/terraform-provider-sbercloud#226]
how can i set the tenant in the terraform code ?

```
provider "sbercloud" {
  auth_url     = "https://iam.ru-moscow-1.hc.sbercloud.ru/v3"
  region       = "ru-moscow-1"
  access_key   = var.access_key
  secret_key   = var.secret_key
  project_name = var.iam_project_name
}
```
where **var.iam_project_name** i use my tenant name

**Comment by Ccaswell42** [comment]
You can set tenant by `account_name`
https://github.com/sbercloud-terraform/terraform-provider-sbercloud/blob/master/docs/index.md
