### ISSUE TITLE
Linking the policy to the Enterprise Project (sbercloud_identity_role_assignment)

### ISSUE THREAD

**Issue by ufo-driver** [sbercloud-terraform/terraform-provider-sbercloud#228]
Hi there,

### Terraform Version
Terraform v1.5.7

### Affected Resource(s)
Please list the resources as a list, for example:
- sbercloud_identity_role_assignment

### Terraform Configuration Files
```hcl
resource "sbercloud_identity_role_assignment" "role_assignment" {
  for_each = local.roles-groups-list

  group_id      = sbercloud_identity_group.groups[each.value.name].id
  role_id       = data.sbercloud_identity_custom_role.role[each.value.role].id
  project_id   ???
  
  depends_on        = [sbercloud_identity_group.groups]
}
```
What argument can be used to bind a policy to a group in the enterprise project space?

**Comment by Ccaswell42** [comment]
You can use argument `enterprise_project_id `. It's not specified in the documentation, but it works. We will fix the documentation in the next release!

```
variable "enterprise_project" {}
variable "role_id" {}
variable "group_id" {}

resource "sbercloud_identity_role_assignment" "role1" {
  role_id    = var.role_id
  group_id   = var.group_id
  enterprise_project_id = var.enterprise_project
}
```

**Comment by ufo-driver** [comment]
│ Error: Unsupported argument
│ 
│   on modules/users/main.tf line 33, in resource "sbercloud_identity_role_assignment" "custom_role_assignment":
│   33:   enterprise_project_id    = var.enterprise_project_id
│ 
│ An argument named "enterprise_project_id" is not expected here.
╵
