### ISSUE TITLE
Get VPC Gateway ID using data

### ISSUE THREAD

**Issue by ufo-driver** [sbercloud-terraform/terraform-provider-sbercloud#231]
Hi there,

Terraform Version
Terraform v1.5.7

Hello, please tell me how I can get the vpn connection ID for the sbercloud_vpc_route resource, with the Route type = vpn parameter.
Thank you.
![image](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/79808282/4babacd1-4ced-4a72-8e73-68b6df442c30)

**Comment by BurMachine** [comment]
Hello, at the moment this functionality is not available. Contact Sales and TAM to leave a request to add.
