### ISSUE TITLE
API doesn't support new syntax of sbercloud_css_cluster

### ISSUE THREAD

**Issue by antonvigo** [sbercloud-terraform/terraform-provider-sbercloud#232]
Hi there,

### Terraform version
1.3.7

### SberCloud provider version
1.11.5

### Affected Resource: 
- sbercloud_css_cluster

### Config:
```hcl
resource "sbercloud_css_cluster" "elasticsearch" {
  name = "ess1"

  engine_type    = "elasticsearch"
  engine_version = "7.6.2"

  ess_node_config {
    flavor          = "ess.spec-4u32g"
    instance_number = 3
    volume {
      volume_type = "HIGH"
      size        = 300
    }
  }

  availability_zone = "ru-moscow-1a"
  vpc_id            = "some_vpc_id"
  subnet_id         = "some_subnet_id"
  security_group_id = "some_secgroup_id"
}

```

### Some `Terraform apply` output:
```
│ Error: Insufficient node_config blocks
│ 
│   on main.tf line 15, in resource "sbercloud_css_cluster" "elasticsearch":
│   15: resource "sbercloud_css_cluster" "elasticsearch" {  
│ 
│ At least 1 "node_config" blocks are required.

│ Error: Unsupported block type
│ 
│   on main.tf line 21, in resource "sbercloud_css_cluster" "elasticsearch":
│   21:   ess_node_config {
│ 
│ Blocks of type "ess_node_config" are not expected here.

│ Error: Unsupported argument
...
│ An argument named "availability_zone" is not expected here.

│ Error: Unsupported argument
...
│ An argument named "vpc_id" is not expected here.

│ Error: Unsupported argument
...
│ An argument named "subnet_id" is not expected here.

│ Error: Unsupported argument
...
│ An argument named "security_group_id" is not expected here.
```

### Expected Behavior
Resource was created.

### Actual Behavior
Unsupported resource syntax

### Conclusion:
Looks like [documentation](https://registry.terraform.io/providers/sbercloud-terraform/sbercloud/latest/docs/resources/css_cluster) was copied from huaweicloud with renaming resource prefix but without corresponging changes in code. I mean last provider version doesn't support new syntax of sbercloud_css_cluster regarding to ess_node_config. I've tried to rollback the code to old syntax version with specifed node_config instead of ess_node_config and it worked fine.

**Comment by BurMachine** [comment]
Hello, at the moment this functionality is not available. Contact Sales and TAM to leave a request to add.
