### ISSUE TITLE
"How to Assign Roles to Scope 'All-Projects' in SberCloud? Missing Info in Docs"

### ISSUE THREAD

**Issue by qukly** [sbercloud-terraform/terraform-provider-sbercloud#241]
Request from AmazMe project

Terraform Version
Terraform v1.1.3
on linux_amd64

Affected Resource(s)
sbercloud_identity_role_assignment

SberCloud has an [API](https://support.hc.sbercloud.ru/api/iam/iam_02_0519.html) that lets you add roles to group with a "all-project" scope, which is different from a global scope. But when I check out the docs for the **sbercloud_identity_role_assignment** resource, there's nothing that tells how to actually do it.

<img width="320" alt="image" src="https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/49863291/a4ac5ae9-aaa7-47d6-9cee-adae9b8d26a6">

If it can't be done now, can you change the provider to make it work? It would really help in case with lots of projects. 
If it can be done, can you guide us how to do it?

Thank you.

**Comment by Ccaswell42** [comment]
You can set `project_id` to all. Like this: 
```
resource "sbercloud_identity_role_assignment" "role1" {
  role_id    = "c81785187cdc4a3fb799fc035e33776f"
  group_id   = var.group_id
  project_id = "all"
}
```

We will add this item to the documentation in the next release.

**Comment by qukly** [comment]
Hi,
Thank you for reply,
**project_id = "all"** works like a charm
