### ISSUE TITLE
Провайдер пересоздает ECS при изменении subnet

### ISSUE THREAD

**Issue by emulatethis777** [sbercloud-terraform/terraform-provider-sbercloud#243]
Провайдер пересоздает ECS при изменении блока network, хотя само облако позволяет менять подсеть и VPC для ECS без пересоздания и рестарта.
![image](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/61944598/3d60d4c9-ceb3-43c3-95c0-d9589a00146a)
![image](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/61944598/b565583a-7e32-4411-a459-a6d96d67818e)

### Terraform Version
Terraform v1.5.2
sbercloud-terraform/sbercloud v1.5.0

### Affected Resource(s)
sbercloud_compute_instance

### Terraform Configuration Files
```hcl
resource "sbercloud_compute_instance" "test-instance" {
  name              = "test-instance"
  image_id          = data.sbercloud_images_image.c7.id
  flavor_id         = "s7n.medium.4"
  key_pair          = "ssh-key"
  security_groups   = ["default"]
  availability_zone = data.sbercloud_availability_zones.zones.names[0]

  system_disk_type = "SSD"
  system_disk_size = "40"

  network {
    uuid = sbercloud_vpc_subnet.subnet1.id
  }
}
```

### Expected Behavior
Изменение блока network не ведёт к пересозданию ECS.

### Actual Behavior
Изменение блока network приводит к пересозданию ECS.

**Comment by Vikontrol** [comment]
Добрый день, чтобы изменения подсети не затрагивали инстанс, используйте отдельный ресурс для подключения подсети к инстансу - sbercloud_compute_interface_attach, в таком случае пересоздания вм не будет. Тоже самое применительно и к дискам, их тоже нужно отдельным ресурсом создавать и атачить: sbercloud_evs_volume и sbercloud_compute_volume_attach
