### ISSUE TITLE
New IAM resources ( eps support )

### ISSUE THREAD

**Issue by Tearix** [sbercloud-terraform/terraform-provider-sbercloud#249]
Add please:
- identity_group_role_assignment
- identity_user_role_assignment

Related PRs:
- https://github.com/huaweicloud/terraform-provider-huaweicloud/pull/2934
- https://github.com/huaweicloud/terraform-provider-huaweicloud/pull/3280

**Comment by Tearix** [comment]
Maybe we should use non-documented enterprise_project_id in sbercloud_identity_role_assignment (https://github.com/sbercloud-terraform/terraform-provider-sbercloud/issues/237 ) ?

**Comment by BurMachine** [comment]
Hello, added in release `v1.11.6`
