### ISSUE TITLE
Add api parametr "alpha.cce/fixPoolMask" support when creating a cluster

### ISSUE THREAD

**Issue by KraMorK** [sbercloud-terraform/terraform-provider-sbercloud#269]
### Terraform Version
 all version

### Affected Resource(s)
- sbercloud_cce_cluster

### Terraform Configuration Files
```hcl
resource "sbercloud_cce_cluster" "test-cluster" {
  ...
  container_network_type = "vpc-router"
  ...
}
```

### Expected Behavior
the provider has the ability to configure a network mask for each node in the "vpc-router" cluster mode. Now the API has this option, through the parameter `alpha.cce/fixPoolMask`, but the provider does not have it

### Actual Behavior
no possibility

### Important Factoids
The API allows you to specify the Alpha.cce/fixPoolMask parameter when creating a cluster; The provider does not have this option. this leads to excessive use of network address space.

**Comment by BurMachine** [comment]
Hello, we are checking the possibility of such changes

**Comment by BurMachine** [comment]
Changes will be added in the next release.

**Comment by AlexDexsoon** [comment]
Hello @BurMachine, do you have any progress so far?

**Comment by BurMachine** [comment]
Hello, the next release is planned for the end of April, beginning of May

**Comment by comotoza** [comment]
Hello! 
Try this one syntax
```
extend_param = {
   "alpha.cce/fixPoolMask" = 24
 }
```
