### ISSUE TITLE
Отсутствует возможность настроить VPN соединение через провайдера

### ISSUE THREAD

**Issue by YakovenkoArtem** [sbercloud-terraform/terraform-provider-sbercloud#273]
Добрый день.

При подключении офисной сети к сети SberCloud Advanced требуется настроить VPN через Terraform.
Но, к большому сожаления, SberCloud провайдер не предоставляет ресурсов вида: "VPN Gateways" и "VPN Connections".
Более того, если есть ресурсы в Terraform зависящие от VPN (например сеть VPC), то ломается terraform apply / destroy, так как Terraform не может удалить сеть, которая используется в VPN соединении.

### Terraform Version
OpenTofu v1.6.2
on windows_386
provider registry.opentofu.org/sbercloud-terraform/sbercloud v1.11.6
provider tf.repo.sbc.space/sbercloud-terraform/sbercloud v1.11.6 

### Affected Resource(s)
- aws_vpn_gateway
- aws_customer_gateway
- aws_vpn_connection

### Expected Behavior
Настройка VPN туннеля до облака SberCloud настраивается через Terraform

### Actual Behavior
Нет возможности настроить туннель через Terraform.
Как следствие, если в Terraform есть ресурсы связанные с VPN (например, VPC сеть), то при команде terraform apply происходит ошибка: error deleting Subnet: timeout while waiting for state to become 'DELETED' (last state: 'ACTIVE', timeout: 10m0s)
![image](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/20043875/ab0e5b3b-dcb6-4596-a6fe-09eb89a43dea)

### Steps to Reproduce
terraform apply
ИЛИ (если используется "православный" инструмент)
tofu apply

### Important Factoids
Стандартный аккаунт в SberCloud Advanced

### References
https://support.huaweicloud.com/intl/en-us/api-vpn/api-vpn.pdf

**Comment by Ccaswell42** [comment]
Добавление данного функционала ожидается до конца мая.

**Comment by YakovenkoArtem** [comment]
Отлично! Очень ждем.

**Comment by nosko-stojachkov** [comment]
@Ccaswell42, Добрый день.
Подскажите пожалуйста когда стоит ожидать релиз функционала?

**Comment by YakovenkoArtem** [comment]
Добрый день.
Конец мая наступил 3 месяца назад.
Когда добавите поддержку создания VPN соединения через скрипт?
Очень нужно.

**Comment by 0ohmresistor** [comment]
Добрый день! 
Функционал добавлен в версии 1.12.3, релиз был сегодня
