### ISSUE TITLE
data sbercloud_dms_kafka_flavors not supported

### ISSUE THREAD

**Issue by J0hnZ0idberg** [sbercloud-terraform/terraform-provider-sbercloud#279]
### Terraform Version
Terraform v1.5.7

### Affected Resource(s)
data sbercloud_dms_kafka_flavors

### Terraform Configuration Files
```hcl
data "sbercloud_dms_kafka_flavors" "test" {
  type               = "cluster"
  flavor_id          = var.flavor_id
  availability_zones = var.availability_zones
  storage_spec_code  = var.storage_spec_code
}
```

### Debug Output

https://gist.github.com/J0hnZ0idberg/46ee84755f6618dd64a6fd521c2c005e

### Expected Behavior
retrun dms  flavors 

### Actual Behavior
 The provider sbercloud-terraform/sbercloud does not support data source
 "sbercloud_dms_kafka_flavors".

### Steps to Reproduce
1. `terraform plan`

### References

- В документации https://registry.terraform.io/providers/sbercloud-terraform/sbercloud/1.11.6/docs/resources/dms_kafka_instance рекомендуется использоваться flavor_id вместо product_id.
- В примере документации указан sbercloud_dms_kafka_flavors.
- Его нет ни в документации, ни в самом провайдере
- Нет ни одного очевидного способа получить flavor_id для создания кластера кафки
- Использования flavor_id вида `kafka.8u16g.cluster`  позволяет создат кластер, однако при повтрном запуске plan появляется diff который в итоге приводит к ошибке ` "c6.8u16g.cluster" -> "kafka.8u16g.cluster"`

Нужно поправить документацию, а также предоставить информацию об альтернативных способах получения flavor_id.

**Comment by J0hnZ0idberg** [comment]
Методом тыка определил соответствие kafka.16u32g.cluster = c6.16u32g.cluster 
Остальное аналогично
И если указывать в формате c6.16u32g.cluster  диффа нет

**Comment by BurMachine** [comment]
Да, все верно, флейворы нужно указывать названиями из консоли(они отображаются в нижней части таблицы выбора флейворов в консоли)

**Comment by tetesh** [comment]
@BurMachine У вас в консоли отображается как kafka.xxx.xxx.xx 
И обновите документацию https://cloud.ru/docs/dms-kafka/ug/topics/overview__specifications#id1
