### ISSUE TITLE
terraform remote backend state reading error

### ISSUE THREAD

**Issue by cexybebe** [sbercloud-terraform/terraform-provider-sbercloud#280]
after applying the terraform configuration, undefined characters are written to the tfstate file, which leads to an error in reading the state file (tfstate) from S3 storage

In the screenshots I attach an example of a broken state file

<img width="506" alt="Screenshot 2024-05-06 at 13 46 34" src="https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/121612321/189d40a7-a103-451f-a912-5788deabe259">

<img width="611" alt="Screenshot 2024-05-06 at 13 46 40" src="https://github.com/sbercloud-terraform/terraform-provider-sbercloud/assets/121612321/45a0d9bc-d109-4bb7-9263-77009c1c0f22">

error down below
│ Error: error loading state: 2 problems:
│ 
│ - Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
│ - Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.
│ 
│ 
╵

**Comment by bottlesbo** [comment]
how you fix it ?

**Comment by cexybebe** [comment]
> how you fix it ?
used gitlab remote terraform state
