### ISSUE TITLE
Получение данных о конкретном флейворе

### ISSUE THREAD

**Issue by phkrl** [sbercloud-terraform/terraform-provider-sbercloud#281]
На данный момент единственный способ получить информацию о флейворе в AZ - это получить список флейворов через data.sbercloud_compute_flavors и выбрать среди них нужный. У такого подхода есть две проблемы: этот data source возвращает ошибку, если не найдено флейворов, подходящих под указанные фильтры, а при успешном выполнении запроса нужна дополнительная логика для выбора флейвора. При этом фильтры являются жёсткими, то есть нельзя указать, например, RAM > 4GB.
В качестве альтернативного решения мы хотели бы иметь возможность получать информацию о конкретном флейворе, для которого заранее известно имя или id. Примерная желаемая схема:
```
data "sbercloud_compute_flavor" "flavor" {
  availability_zone = "ru-moscow-1a"
  id = "c3.large.2"
}
```
Возвращаемые поля (необходимые):
- `cpu_count`
-  `memory_size`
- `performance_type`
- `generation`
Возможные дополнительные поля:
- `disk_size`
- `gpus`

**Comment by BurMachine** [comment]
Добрый день, на данный момент реализация такого функционала невозможна.
