### ISSUE TITLE
error creating RDS instance

### ISSUE THREAD

**Issue by AlexBaturo** [sbercloud-terraform/terraform-provider-sbercloud#286]
Добрый день!
При создании инстанса БД в облаке через terraform стала появляться ошибка

`{"error_msg":"Invalid specifications.","error_code":"DBS.280239"}`

перестали даже раскатываться ранее созданные через terraform инстансы БД
```
terraform --version
Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.21.0
+ provider registry.terraform.io/sbercloud-terraform/sbercloud v1.12.0
```
Что могло поменяться?

**Comment by BurMachine** [comment]
Добрый день, пришлите пожалуйста ваш примерный манифест. Предварительно ошибка говорит о том, что инстанс с такой спецификацией либо не доступен, либо не существует в данной зоне доступности.

**Comment by AlexBaturo** [comment]
Проблему удалось устранить!
Почему-то flavor rds.pg.c6.large.2.ha перестал быть нам доступен, заменили его на rds.pg.n1.large.2 и изменили тип хранилища с HIGH на CLOUDSSD после этого все заработало

не подскажете что случилось с  flavor rds.pg.c6.large.2.ha ?

**Comment by BurMachine** [comment]
Флейвор мог быть "Sold out", мог не входить в instance class или при переходе на другую az мог там не существовать
