### ISSUE TITLE
Нет опции ssl_enable для DCS

### ISSUE THREAD

**Issue by el4v** [sbercloud-terraform/terraform-provider-sbercloud#293]
Добрый день, сейчас нет возможности с помощью терраформ включить опцию ssl_enable

В следующей версии провайдера huawei есть такая опция, планируется ли добавление в провадер сберклауда?

**Comment by BurMachine** [comment]
Добрый день, добавим в следующем релизе

**Comment by 0ohmresistor** [comment]
@el4v Добрый день!
Провайдер обновился, теперь такая опция есть. 
Пример:
```
resource "sbercloud_dcs_instance" "instance_1" {
  name               = "redis_single_instance"
  engine             = "Redis"
  engine_version     = "5.0"
  capacity           = 0.125
  flavor             = "redis.single.xu1.tiny.128"
  availability_zones = ["ru-moscow-1a"]
  password           = "YourPassword@123"
  vpc_id             = ""
  subnet_id          = ""
  ssl_enable         = false
}
```

**Comment by 0ohmresistor** [comment]
Также обратите внимание, что `ssl_enable = true` работает с версией Redis = 6.0

**Comment by el4v** [comment]
супер, спасибо
