### ISSUE TITLE
Ecs.0043 rootVolume type[GPSSD] is not exist

### ISSUE THREAD

**Issue by iamkpd** [sbercloud-terraform/terraform-provider-sbercloud#295]
Добрый день, с чем может быть связана ошибка:
rror: error creating server: Bad request with: [POST https://ecs.ru-moscow-1.hc.sbercloud.ru/v1.1/1286819e840026df2f50c013061d0705/cloudservers], request_id: eafa62c7e550069f6791059212b422f4, error message: {"error":{"message":"rootVolume type[GPSSD] is not exist.","code":"Ecs.0005","details":[{"code":"Ecs.0043"}]}}

**Comment by BurMachine** [comment]
Добрый день! Мы откатились до версии 1.12.0, при использовании которой не будет таких ошибок
