### ISSUE TITLE
Error creating IAM user

### ISSUE THREAD

**Issue by oboz-online** [sbercloud-terraform/terraform-provider-sbercloud#298]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

terraform version 1.5.7

Hello, I have error when creating IAM user. But role and group creates successfully

sbercloud_identity_user.user_1: Creating...
╷
│ Error: error creating IAM user: Bad request with: [POST https://iam.ru-moscow-1.hc.sbercloud.ru/v3.0/OS-USER/users], request_id: 08cd9bf62dd8c941051b2e5c57f7d34b, error message: {"errorcode":["1101"]}
│
│   with sbercloud_identity_user.user_1,
│   on main.tf line 88, in resource "sbercloud_identity_user" "user_1":
│   88: resource "sbercloud_identity_user" "user_1" {

Manifest text:
terraform {
  required_providers {
    sbercloud = {
      source = "sbercloud-terraform/sbercloud" # Initialize Advanced provider
    }
  }
}

# Configure Advanced provider
provider "sbercloud" {
  auth_url = "https://***********.sbercloud.ru/v3" # Authorization address
  region   = "**-*********"                                # The region where the cloud infrastructure will be deployed

  # Authorization keys
  access_key = var.access_key
  secret_key = var.secret_key
}

resource "sbercloud_identity_role" "role_1" {
  name        = "tfrole_1"
  description = "created by terraform"
  type        = "AX"
  policy      = <<EOF

{
    "Version": "1.1",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "obs:object:PutObject",
                "obs:bucket:ListBucketVersions",
                "obs:object:GetObjectAcl",
                "obs:bucket:GetDirectColdAccessConfiguration",
                "obs:bucket:GetBucketLocation",
                "obs:bucket:GetBucketNotification",
                "obs:bucket:GetEncryptionConfiguration",
                "obs:object:DeleteObjectVersion",
                "obs:bucket:GetBucketWebsite",
                "obs:object:RestoreObject",
                "obs:bucket:GetBucketLogging",
                "obs:bucket:GetBucketTagging",
                "obs:bucket:GetLifecycleConfiguration",
                "obs:bucket:ListBucketMultipartUploads",
                "obs:object:GetObjectVersionAcl",
                "obs:bucket:GetBucketCustomDomainConfiguration",
                "obs:object:DeleteObject",
                "obs:bucket:GetBucketVersioning",
                "obs:bucket:HeadBucket",
                "obs:bucket:GetBucketInventoryConfiguration",
                "obs:object:ModifyObjectMetaData",
                "obs:object:GetObjectVersion",
                "obs:object:GetObject",
                "obs:bucket:PutLifecycleConfiguration",
                "obs:bucket:ListBucket",
                "obs:bucket:GetReplicationConfiguration",
                "obs:object:AbortMultipartUpload",
                "obs:bucket:GetBucketPolicy",
                "obs:object:ListMultipartUploadParts",
                "obs:bucket:GetBucketQuota",
                "obs:bucket:GetBucketStoragePolicy",
                "obs:bucket:GetBucketAcl",
                "obs:bucket:GetBucketCORS",
                "obs:bucket:GetBucketStorage"
            ],
            "Resource": [
                "OBS:*:*:object:*",
                "OBS:*:*:bucket:**********",
                
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "obs:bucket:ListAllMyBuckets"
            ]
        }
    ]
}
EOF
}

resource "sbercloud_identity_group" "group_1" {
  name        = "trgroup_1"
  description = "This is a test group"
}

resource "sbercloud_identity_user" "user_1" {
  name = "tf_1"
  #email        = null
  #phone        = null
  #country_code = null
  # description = "TF user"
  # password    = var.password
  # pwd_reset   = true
  # enabled     = true
  # access_type = "default"
}

resource "sbercloud_identity_group_membership" "membership_1" {
  group = sbercloud_identity_group.group_1.id
  users = [
    sbercloud_identity_user.user_1.id,
  ]
}

resource "sbercloud_identity_role_assignment" "role_assignment_1" {
  role_id    = sbercloud_identity_role.role_1.id
  group_id   = sbercloud_identity_group.group_1.id
  project_id = var.project_id
}

### Affected Resource(s)
Please list the resources as a list, for example:
- sbercloud_identity_user
- sbercloud_identity_role
- sbercloud_identity_group
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by 0ohmresistor** [comment]
Hello, this error occurs due to an incorrect username. In your case, the username must be longer than 5 characters.
