### ISSUE TITLE
Broken URL to 1.12.1 in opentofu registry

### ISSUE THREAD

**Issue by pavel-trubitsyn** [sbercloud-terraform/terraform-provider-sbercloud#299]
Hi there,

Opentofu registry has broken URL to provider 1.12.1
https://github.com/opentofu/registry/blob/main/providers/s/sbercloud-terraform/sbercloud.json

shasums_url returns 404.
(https://github.com/sbercloud-terraform/terraform-provider-sbercloud/releases/download/v1.12.1/terraform-provider-sbercloud_1.12.1_SHA256SUMS)

**Comment by BurMachine** [comment]
Good afternoon, we have temporarily returned to version 1.12.0
