### ISSUE TITLE
Problem with creating lts_group

### ISSUE THREAD

**Issue by zradeg** [sbercloud-terraform/terraform-provider-sbercloud#305]
Greetings!
I'm trying to create a lts_group with lts_stream, using the syntax from the documentation:

```
resource "sbercloud_lts_group" "pier_prod_pg" {
  group_name = "pier-prod-pg"
  region     = "ru-moscow-1"
  ttl_in_days = 15
}

resource "sbercloud_lts_stream" "pier_prod_pg" {
  group_id              = sbercloud_lts_group.pier_prod_pg.id
  region                = "ru-moscow-1"
  stream_name           = "pier-prod-pg"
  ttl_in_days           = null
}
```

But I get an error:
```
Error: error updating log group: Resource not found: [POST https://lts.ru-moscow-1.hc.sbercloud.ru/v2/xxx/groups/xxx], request_id: xxx, error message: {"error_msg":"The API does not exist: method POST not found","error_code":"APIGW.0101","request_id":"xxx"}
│ 
│ 
│   with sbercloud_lts_group.pier_prod_pg,
│   on logging.tf line 39, in resource "sbercloud_lts_group" "pier_prod_pg":
│   39: resource "sbercloud_lts_group" "pier_prod_pg" {
```

What is the error related to and how can I fix it?

Also, I have a question: is it planned to implement the Log Transfer setting? If so, when can we expect it?

**Comment by 0ohmresistor** [comment]
Greetings!
We have updated provider today, and your code from above works without errors. Regarding your second question, we will add this functionality in the next release; you better create a new issue for this and mark it as feature request.

**Comment by zradeg** [comment]
> Greetings! We have updated provider today, and your code from above works without errors. Regarding your second question, we will add this functionality in the next release; you better create a new issue for this and mark it as feature request.

Thanks, it works now.
By the way, the provider is available only by the source "sbercloud-terraform/sbercloud", not by "tf.repo.sbc.space/sbercloud-terraform/sbercloud" - this source option throws an error when trying:
```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider tf.repo.sbc.space/sbercloud-terraform/sbercloud: no available releases match the
given constraints ~> 1.12.2
```

Regarding your recommendation to create a Feature Request - I did not find an option on how to do this in Issues. I don't have enough privileges? Or did you mean to create another regular Issue with a request to add functionality?

**Comment by zradeg** [comment]
> Regarding your second question, we will add this functionality in the next release; you better create a new issue for this and mark it as feature request.

I hope I did everything right: https://github.com/sbercloud-terraform/terraform-provider-sbercloud/issues/309

**Comment by 0ohmresistor** [comment]
Yes, everything is right. 
The provider version update in the cloud is delayed, so the newest version is currently only available on github. If problem lts_group is resolved, this issue should be closed
