### ISSUE TITLE
Problems with creating sbercloud_network_acl_rule

### ISSUE THREAD

**Issue by ngoral** [sbercloud-terraform/terraform-provider-sbercloud#311]
### Terraform Version
1.5.7

### Affected Resource(s)
sbercloud_network_acl_rule

### Terraform Configuration Files
```hcl
resource "sbercloud_network_acl_rule" "nacl_inbound_rule_1" {
  name                   = "nacl_inbound_rule_1"
  protocol               = "tcp"
  action                 = "allow"
  source_ip_address      = "0.0.0.0/0"
  destination_ip_address = sbercloud_vpc_subnet.my_subnet.cidr
  destination_port       = "80,443" # does not accept this
  description            = "inbound traffic from internet"
  enabled                = true
}
resource "sbercloud_network_acl_rule" "inbound_rule_2" {
 name                   = "nacl_inbound_rule_2"
 protocol               = "any" # does not accept this
 action                 = "allow"
 source_ip_address      = sbercloud_vpc_subnet.my_subnet.cidr
 destination_ip_address = sbercloud_vpc_subnet.my_subnet.cidr
 # destination_port       = "1:65535" # requires this, although docs state that is not required
 description            = "some other"
 enabled                = true
}
```

### Expected Behavior
I would expect this code to create two network acl rules. One that allows TCP traffic from any IP to ports 80 and 443 of `my_subnet`
And other that allows any protocol traffic to any port inside of `my_subnet`.

### Actual Behavior
I got several errors while trying to apply this kind of code:
```
Bad request with: [POST https://vpc.ru-moscow-1.hc.sbercloud.ru/v2.0/fwaas/firewall_rules], request_id: ..., error message: {"NeutronError":{"message":"Invalid input for destination_port. Reason: Port '80,443' is not a valid number..","type":"HTTPBadRequest","detail":""}}
```
(Well, this option is not stated in docs, but is highly desireable since it can be done in UI, and also `terraform validate` does not have anything against this form)

```
Bad request with: [PUT https://vpc.ru-moscow-1.hc.sbercloud.ru/v2.0/fwaas/firewall_rules/...], request_id: ..., error message: {"NeutronError":{"message":"'destination_port' attribute isn't allowed 'empty'","type":"HTTPBadRequest","detail":""}}
```
Although docs [state](https://registry.terraform.io/providers/sbercloud-terraform/sbercloud/latest/docs/resources/network_acl_rule#destination_port) that `destination_port` is optional. Also, if trying to import already existing rules, that have "All" in UI, using `1:65535` will result in diff, because terraform thinks that "All" is `0:65535`
This error also is not caugth by `terraform validate`

```
Bad request with: [PUT https://vpc.ru-moscow-1.hc.sbercloud.ru/v2.0/fwaas/firewall_rules/...], request_id: ...., error message: {"NeutronError":{"message":"Firewall Rule protocol any is not supported. Only protocol values [tcp, udp, icmp, icmpv6] and their integer representation (0 to 255) are supported.","type":"FirewallRuleInvalidProtocol","detail":""}}
```
I think this one is self-explainatory. I definetely do not want to create separate rule for every protocol. Docs says that `any` is allowed and this also is not caught by `terraform validate`

**Comment by ngoral** [comment]
Also, when trying to import already existing rules if describing `destination_port` with just one number, I get following error:
`Bad request with: [PUT https://vpc.ru-moscow-1.hc.sbercloud.ru/v2.0/fwaas/firewall_rules/...], request_id: ..., error message: {"NeutronError": {"detail": "", "type": "FirewallRuleAttributeExclusion", "message": "Firewall Rule attributes destination_multiport destination_port, only one attribute can be assigned"}}`

But `destination_multiport` does not pass `terraform validate`, as there is no such attribute

**Comment by 0ohmresistor** [comment]
Greetings!
There is no such functionality as comma-separated list of ports. You can specify a range of ports, using ":" operator. If you need more ports, then you need to create a separate rule for each one. 
Speaking of the error that does not accept the "any" type, that's a bug in documentation. API was updated and it can't accept type "any". We will fix .md description in the next provider release.

**Comment by 0ohmresistor** [comment]
We have updated the doc in the latest release.
