### ISSUE TITLE
Не получается инициализировать terraform

### ISSUE THREAD

**Issue by DY-MS** [sbercloud-terraform/terraform-provider-sbercloud#321]
Здравствуйте.
Не получается инициализировать terraform.
Делаю всё по вашей инструкции, но не можем обойти ошибку при инициализации
пишет, что нет подходящего дистра, но это ж не так - см debug output.
С вашей репы скачал версию провайдера 1.12.3, но не получается его скормить terraform'у.
Подскажите пожалуйста куда копать?

### Terraform Version
1.9.7

### Affected Resource(s)
Terraform init

### Terraform Configuration Files
main.tf 
```
terraform {
  required_providers {
    sbercloud = {
      source = "sbercloud-terraform/sbercloud"
    }
  }
}

provider "sbercloud" {
  auth_url = "https://iam.ru-moscow-1.hc.sbercloud.ru/v3" 
  region   = "ru-moscow-1"

  # Authorization keys
  access_key = var.access_key
  secret_key = var.secret_key
}
``` 
.terraformrc
```
provider_installation {
   network_mirror {
      url = "https://terraform.cloud.ru/"
      include = ["registry.terraform.io/*/*"]
   }
   direct {
      exclude = ["registry.terraform.io/*/*"]
   }
}
``` 

### Debug Output
https://gist.github.com/DY-MS/e63e88ede9b6e6dc902e78e9c2a09364

**Comment by 0ohmresistor** [comment]
Здравствуйте!
Попробуйте сделать следующим образом:
1. Скачайте скомпилированный бинарник (или скомпилируйте из исходников)
2. Положите его в папку /Users/user/go/bin/
3. Измените .terraformrc, чтобы было так
```
provider_installation {
  dev_overrides {
    "mycloud.com/myorg/sbercloud" = "/Users/user/go/bin/"
  }
  direct {}
}
```
4. В файле main.tf измените инициализацию как приведено ниже
```
terraform {
  required_providers {
    sbercloud = {
      source  = "mycloud.com/myorg/sbercloud"
    }
  }
}
provider "sbercloud" {
  auth_url = "https://iam.ru-moscow-1.hc.sbercloud.ru/v3" 
  region   = "ru-moscow-1" 
  access_key = var.access_key
  secret_key = var.secret_key
}
``` 
Таким образом, вы будете использовать локальную версию провайдера, а не подтягивать её из облака

**Comment by J0hnZ0idberg** [comment]
Используйте зеркала. Вы не можете инициализировать из-за того, что по умолчанию провайдер тянется с реджистри терраформ, а он банит айпи РФ. Инструкция тут может быть полезна https://cloud.ru/docs/terraform/ug/topics/guides__mirrors.html

**Comment by DY-MS** [comment]
Помогла смена зеркал с cloud.ru на yandex
