### ISSUE TITLE
Authentication failed with provider["registry.terraform.io/sbercloud-terraform/sbercloud"],

### ISSUE THREAD

**Issue by IPangeya** [sbercloud-terraform/terraform-provider-sbercloud#331]
Добрый день
Пробую развернуть с помощью terraform ВМ из примера, размещенного на examples/main.tf](https://github.com/sbercloud-terraform/terraform-provider-sbercloud/blob/master/examples/main.tf

Падает с ошибкой
$terraform plan
╷
│ Error: Authentication failed
│ 
│   with provider["registry.terraform.io/sbercloud-terraform/sbercloud"],
│   on main.tf line 26, in provider "sbercloud":
│   26: provider "sbercloud" {

Код из строки 26 файла main
provider "sbercloud" {
  auth_url = "https://iam.ru-moscow-1.hc.sbercloud.ru/v3"
  region   = "ru-moscow-1"

  access_key   = var.access_key
  secret_key   = var.secret_key

Ключи сгенерировала и положила в файл terraform.tfvars

$ terraform -v
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/sbercloud-terraform/sbercloud v1.12.4

**Comment by 0ohmresistor** [comment]
Добрый день! 
Если положить ключи в файл variables.tf, который будет выглядеть как:
```
variable "access_key" {
  default = " "
}

variable "secret_key" {
  default = " "
}
```
Или задать напрямую в коде, то ошибка сохранится?

**Comment by IPangeya** [comment]
да, такие варианты пробовала, ошибка сохраняется

**Comment by 0ohmresistor** [comment]
Вы создаёте IAM пользователя как написано по ссылке выше? Если да, то попробуйте пропустить этот шаг и сгенерировать ключи для того аккаунта, в который вы попадаете по кнопке "перейти в консоль" из личного кабинета. Соответственно, access key - это второй столбец из таблицы, которая скачается (20 символов длиной, secret key - это последний столбец. При авторизации через пару AK/SK, которая создана в разделе my credentials, токен не нужен
